name: listview
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.0.0
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  video_player: ^2.0.0
  fluttertoast: any
  flutter_localizations: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - data/Ejemplo.json
      - assets/
      - assets/ypf.png
